# Use postgres/example user/password credentials
#version: '3.9'

services:

  postgres:
    container_name: my_db
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twit_db
      - log_destination=stderr
      - logging_collector=on
      - log_directory=/var/lib/postgresql/log

    ports:
      - 5432:5432
    networks:
      - my_net

    volumes:
      - ./db/:/var/lib/postgresql/data

networks:
  my_net:
    driver: bridge