# Use postgres/example user/password credentials
#version: '3.9'

services:

  app:
    container_name: my_app
    build: ./src
    #command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    networks:
      - my_net

  postgres:
    container_name: my_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twit_db
      - log_destination=stderr

    ports:
      - 5432:5432
    networks:
      - my_net

    volumes:
      - ./db/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Добавление инициализации


networks:
  my_net:
    driver: bridge