name: Python application

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
    - name: Test with flake8
      run: |
        flake8 src
    - name: Test with black
      run: |
        black src
    - name: Test with isort
      run: |
        isort src
    - name: Test with mypy
      run: |
        mypy src

